# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

VERSION_TUPLE = tuple[int | str, ...]
COMMIT_ID = str | None

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = "0.1.dev105+ga84e5f7ce.d20251027"
__version_tuple__ = version_tuple = (0, 1, "dev105", "ga84e5f7ce.d20251027")

__commit_id__ = commit_id = None
