"""Type stubs for genson library."""

from typing import Any, Dict

class SchemaBuilder:
    def __init__(self, schema_uri: str | None = None) -> None: ...
    def add_object(self, obj: Any) -> None: ...
    def add_schema(self, schema: Dict[str, Any]) -> None: ...
    def to_schema(self) -> Dict[str, Any]: ...