# Field mappings between NMDC, GOLD, and enrichment outputs
# This file defines how fields from different sources map to common concepts
# 
# Priority lists define the order to check fields (first found wins)
# Mapping rules define how to extract and transform field values

# Location fields
location:
  latitude:
    nmdc:
      - path: "lat_lon[0]"
        type: "array_index"
      - path: "latitude"
        type: "direct"
    gold:
      - path: "latitude"
        type: "direct"
      - path: "location.latitude"
        type: "nested"
    enrichment:
      - path: "location.latitude"
        type: "nested"
  
  longitude:
    nmdc:
      - path: "lat_lon[1]"
        type: "array_index"
      - path: "longitude"
        type: "direct"
    gold:
      - path: "longitude"
        type: "direct"
      - path: "location.longitude"
        type: "nested"
    enrichment:
      - path: "location.longitude"
        type: "nested"
  
  elevation:
    nmdc:
      - path: "elev"
        type: "direct"
      - path: "elevation"
        type: "direct"
    gold:
      - path: "elevation"
        type: "direct"
      - path: "altitudeMeters"
        type: "direct"
    enrichment:
      - path: "elevation.value"
        type: "nested"
      - path: "elevation_m"
        type: "direct"
  
  country:
    nmdc:
      - path: "geo_loc_name"
        type: "parse_first"  # Parse first part before colon
    gold:
      - path: "country"
        type: "direct"
      - path: "geoLocation"
        type: "parse_country"
    enrichment:
      - path: "reverse_geocoding.country"
        type: "nested"
      - path: "location.country"
        type: "nested"
  
  state_province:
    nmdc:
      - path: "geo_loc_name"
        type: "parse_second"  # Parse second part after colon
    gold:
      - path: "state"
        type: "direct"
      - path: "stateProvince"
        type: "direct"
    enrichment:
      - path: "reverse_geocoding.state"
        type: "nested"
      - path: "location.state_province"
        type: "nested"

# Climate/Weather fields
climate:
  temperature:
    nmdc:
      - path: "temp"
        type: "direct"
      - path: "temperature"
        type: "direct"
    gold:
      - path: "temperature"
        type: "direct"
      - path: "envTemperature"
        type: "direct"
    enrichment:
      - path: "weather.temperature"
        type: "nested"
      - path: "climate.temperature_c"
        type: "direct"
  
  precipitation:
    nmdc:
      - path: "annual_precpt"
        type: "direct"
      - path: "precipitation"
        type: "direct"
    gold:
      - path: "precipitation"
        type: "direct"
      - path: "annualPrecipitation"
        type: "direct"
    enrichment:
      - path: "weather.precipitation"
        type: "nested"
      - path: "climate.precipitation_mm"
        type: "direct"
  
  humidity:
    nmdc:
      - path: "humidity"
        type: "direct"
      - path: "rel_humidity_soil"
        type: "direct"
    gold:
      - path: "humidity"
        type: "direct"
      - path: "relativeHumidity"
        type: "direct"
    enrichment:
      - path: "weather.humidity"
        type: "nested"
      - path: "climate.humidity_percent"
        type: "direct"

# Soil fields
soil:
  soil_type:
    nmdc:
      - path: "soil_type"
        type: "direct"
      - path: "soil_text_class"
        type: "direct"
    gold:
      - path: "soilClass"
        type: "direct"
      - path: "soilType"
        type: "direct"
    enrichment:
      - path: "soil.classification"
        type: "nested"
      - path: "soil_type"
        type: "direct"
  
  ph:
    nmdc:
      - path: "ph"
        type: "direct"
      - path: "soil_ph"
        type: "direct"
    gold:
      - path: "soilPh"
        type: "direct"
      - path: "ph"
        type: "direct"
    enrichment:
      - path: "soil.ph"
        type: "nested"
      - path: "soil_properties.ph"
        type: "nested"
  
  organic_carbon:
    nmdc:
      - path: "tot_org_carb"
        type: "direct"
      - path: "org_carb"
        type: "direct"
    gold:
      - path: "organicCarbon"
        type: "direct"
      - path: "totalOrganicCarbon"
        type: "direct"
    enrichment:
      - path: "soil.organic_carbon"
        type: "nested"
      - path: "soil_properties.soc"
        type: "nested"

# Vegetation/Land Use fields
vegetation:
  land_cover:
    nmdc:
      - path: "cur_vegetation"
        type: "direct"
      - path: "current_vegetation"
        type: "direct"
    gold:
      - path: "landUse"
        type: "direct"
      - path: "vegetationType"
        type: "direct"
    enrichment:
      - path: "land_cover.classification"
        type: "nested"
      - path: "ecosystem.land_cover"
        type: "nested"
  
  ecosystem_type:
    nmdc:
      - path: "ecosystem_type"
        type: "direct"
      - path: "env_broad_scale"
        type: "direct"
    gold:
      - path: "ecosystem"
        type: "direct"
      - path: "biome"
        type: "direct"
    enrichment:
      - path: "ecosystem.type"
        type: "nested"
      - path: "ecoregion.biome"
        type: "nested"

# Temporal fields
temporal:
  collection_date:
    nmdc:
      - path: "collection_date"
        type: "direct"
      - path: "collection_date_inc"
        type: "direct"
    gold:
      - path: "collectionDate"
        type: "direct"
      - path: "dateCollected"
        type: "direct"
    enrichment:
      - path: "collection_date"
        type: "direct"
  
  collection_time:
    nmdc:
      - path: "collection_time"
        type: "direct"
      - path: "collection_time_inc"
        type: "direct"
    gold:
      - path: "collectionTime"
        type: "direct"
      - path: "timeCollected"
        type: "direct"
    enrichment:
      - path: "collection_time"
        type: "direct"

# Data type categories for metrics reporting
data_types:
  - name: "Elevation"
    category: "location"
    field: "elevation"
  - name: "Place Name"
    category: "location"
    fields: ["country", "state_province"]
  - name: "Temperature"
    category: "climate"
    field: "temperature"
  - name: "Precipitation"
    category: "climate"
    field: "precipitation"
  - name: "Soil Type"
    category: "soil"
    field: "soil_type"
  - name: "Soil pH"
    category: "soil"
    field: "ph"
  - name: "Land Cover"
    category: "vegetation"
    field: "land_cover"
  - name: "Ecosystem Type"
    category: "vegetation"
    field: "ecosystem_type"

# Field priority lists - order matters (first found wins)
# Extracted from hardcoded values in adapters.py

field_priorities:
  # Location text extraction priorities
  location_text:
    nmdc:
      - "geo_loc_name"
      - "geographic_location"
      - "location"
      - "sample_collection_site"
      - "description"
    gold:
      - "geoLocation"
      - "geographicLocation"
      - "sampleCollectionSite"
      - "description"
      - "habitat"

  # Date field extraction priorities
  date_fields:
    nmdc:
      - "collection_date"
      - "collection_date_inc"
      - "collection_timestamp"
    gold:
      - "dateCollected"
      - "collectionDate"
      - "sampleCollectionDate"

  # ID field mappings for extraction
  gold_id_fields:
    # GOLD ID fields in NMDC documents
    - "gold_biosample_id"
    - "biosampleGoldId"
    - "gold_id"
    - "gold_biosample_identifiers"
    
  nmdc_id_fields:
    # NMDC ID fields in GOLD documents
    - "nmdc_biosample_id"
    - "biosampleNmdcId"
    - "nmdc_id"

  # Known external ID field mappings  
  external_id_mappings:
      "insdc_biosample_identifiers": "external_database_identifiers"
      "ncbi_biosample_identifiers": "external_database_identifiers"
      "jgi_portal_identifiers": "external_database_identifiers"
      "samp_name": "sample_identifiers"
      "name": "sample_identifiers"

  # Host-specific field detection
  host_fields:
    # Direct host fields that indicate host association
    direct_host_fields:
      - "host_name"
      - "host_taxid"
      - "host_common_name"
      - "host_subject_id"
      - "host_body_site"
      - "host_body_habitat"
      - "hostName"
      - "hostScientificName"
      - "hostCommonName"
      - "hostTaxonomyId"

  # Study association fields
  study_fields:
    nmdc:
      - "associated_studies"
      - "part_of"
    gold:
      - "studyGoldId"
      - "projectGoldId"

# Coordinate parsing configurations
coordinate_parsing:
  nmdc:
    # Handles different lat_lon formats in NMDC
    lat_lon_formats:
      - type: "string_space"        # "42.3601 -71.0928"
        pattern: "\\s+"
      - type: "string_comma"        # "42.3601,-71.0928"
        pattern: ","
      - type: "dict"                # {"latitude": 42.3601, "longitude": -71.0928}
        lat_key: "latitude"
        lon_key: "longitude"
      - type: "array"               # [42.3601, -71.0928]
        lat_index: 0
        lon_index: 1
  
  gold:
    # GOLD typically uses separate latitude/longitude fields
    separate_fields:
      latitude: "latitude"
      longitude: "longitude"

# Date parsing configurations
date_parsing:
  formats:
    - format: "iso_datetime"        # "2014-11-25T10:30:00Z"
      pattern: "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}"
      output: "%Y-%m-%d"
    - format: "date_only"           # "2014-11-25"
      pattern: "\\d{4}-\\d{2}-\\d{2}"
      output: "%Y-%m-%d"
    - format: "year_month"          # "2014-11"
      pattern: "\\d{4}-\\d{2}"
      output: "%Y-%m-01"
    - format: "year_only"           # "2014"
      pattern: "\\d{4}"
      output: "%Y-01-01"
  
  # NMDC structured date handling
  nmdc_structured:
    container_key: "has_raw_value"
    type_key: "type"
    expected_type: "nmdc:TimestampValue"