# Configuration for detecting host-associated samples
# This file defines keywords and patterns for identifying samples that are
# associated with hosts (humans, animals, plants) rather than environmental samples

# Keywords that indicate host association
host_keywords:
  # Human-associated
  - gut
  - intestinal
  - fecal
  - stool
  - saliva
  - oral
  - skin
  - nasal
  - vaginal
  - blood
  - tissue
  - organ
  - clinical
  - patient
  - human
  - urine
  - sputum
  - mucus
  
  # Animal-associated
  - mouse
  - rat
  - animal
  - veterinary
  - rumen
  - cecum
  
  # Plant-associated
  - rhizosphere
  - phyllosphere
  - endophyte
  - plant
  - root
  - leaf
  - stem
  - seed
  - flower
  - fruit
  
  # General host-associated
  - host
  - symbiont
  - microbiome
  - pathogen
  - commensal
  - parasite
  
  # Controlled environments
  - greenhouse
  - laboratory
  - culture
  - isolate

# Fields to check for host indicators in NMDC samples
nmdc_host_fields:
  # ENVO fields
  - env_broad_scale
  - env_local_scale
  - env_medium
  
  # Descriptive fields
  - ecosystem_type
  - ecosystem_category
  - ecosystem_subtype
  - sample_type
  - material
  - biome
  - feature
  
  # Direct host fields
  - host_name
  - host_taxid
  - host_common_name
  - host_subject_id
  - host_body_site
  - host_body_habitat
  - host_body_product

# Fields to check for host indicators in GOLD samples
gold_host_fields:
  # Ecosystem path
  - ecosystemPath
  - ecosystem_path
  
  # Descriptive fields
  - sampleType
  - sample_type
  - material
  - biome
  - habitat
  - isolationSource
  
  # Direct host fields
  - hostName
  - host_name
  - hostScientificName
  - hostCommonName
  - host_common_name
  - hostTaxonomyId
  - host_taxid

# Ecosystem paths that indicate host association (GOLD)
gold_host_ecosystem_paths:
  # These are prefixes to check in the ecosystem path
  - "Host-associated"
  - "host-associated"
  - "Host associated"
  
# Ecosystem paths that are definitely environmental (for exclusion)
environmental_ecosystem_paths:
  - "Environmental > Aquatic > Marine"
  - "Environmental > Aquatic > Freshwater"
  - "Environmental > Terrestrial > Soil"
  - "Environmental > Terrestrial > Deep subsurface"
  - "Environmental > Air"

# ENVO terms that indicate host association
# These are ENVO IDs or labels that definitively indicate host association
host_envo_terms:
  # Human-associated
  - "UBERON:0001988"  # feces
  - "UBERON:0001836"  # saliva
  - "UBERON:0002107"  # liver
  - "ENVO:01001026"   # human gut environment
  
  # Plant-associated
  - "ENVO:00002034"   # rhizosphere
  - "ENVO:00002035"   # phyllosphere
  - "ENVO:01001055"   # plant root environment
  
  # General host-associated
  - "ENVO:00002003"   # host-associated habitat
  - "ENVO:01000985"   # host microbiome