name: Deploy Enrichment Metrics to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  workflow_dispatch:
    inputs:
      nmdc_samples:
        description: 'Number of NMDC samples to evaluate'
        required: false
        default: '500'
      gold_samples:
        description: 'Number of GOLD samples to evaluate'
        required: false
        default: '500'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # Only deploy to Pages on push to main or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .
      
      - name: Set sample sizes
        id: samples
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "nmdc_samples=${{ github.event.inputs.nmdc_samples }}" >> $GITHUB_OUTPUT
            echo "gold_samples=${{ github.event.inputs.gold_samples }}" >> $GITHUB_OUTPUT
          else
            echo "nmdc_samples=500" >> $GITHUB_OUTPUT
            echo "gold_samples=500" >> $GITHUB_OUTPUT
          fi
      
      # TODO: Metrics evaluation disabled - requires MongoDB access not available in CI
      # Will need to add file-based input option for CI deployment
      - name: Create placeholder dashboard
        run: |
          # Create pages directory
          mkdir -p pages
          
          # Create placeholder index.html
          cat > pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Biosample Enrichment Metrics Dashboard</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
          </head>
          <body>
              <div class="container mt-5">
                  <h1 class="text-center">🔬 Biosample Enrichment Metrics Dashboard</h1>
                  <div class="alert alert-info mt-4">
                      <h4>Dashboard Currently Unavailable</h4>
                      <p>Metrics evaluation requires MongoDB access which is not available in CI.</p>
                      <p>To generate metrics locally, run: <code>make metrics-local</code></p>
                      <p>A file-based input option will be added in the future for CI deployment.</p>
                  </div>
                  <div class="text-muted text-center mt-4">
                      <small>Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")</small>
                  </div>
              </div>
          </body>
          </html>
          EOF
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'pages'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2